### ISSUE TITLE
Touch Events are not working

### ISSUE THREAD

**Issue by pierrebeaucamp** [playif/play_pixi#2]
Neither the examples nor my own code is working with touch events (touchstart, touchend or touchmove). I could only test this with Chrome on Android on two different phones.

I tried editing _interaction-manager.dart_ and replaced 

``` dart
domElement.addEventListener('touchStart', this.onTouchStart, true);
```

with

``` dart
    this.subscription = domElement.onTouchStart.listen(this.onTouchStart);
```

but this didn't solve the problem for me.

Using straight Dart without pixi works fine:

``` dart
querySelector("canvas").onTouchStart( ... )
```

**Comment by playif** [comment]
This is because that I made some workaround for touch event so that can work correctly on CocoonJS, but not in Chrome.

I will fix it by checking the environment in advance.

**Comment by playif** [comment]
Hi @pierrebeaucamp ,
I fixed the bug. Please upgrade your packages.

Thanks for your reporting.

**Comment by pierrebeaucamp** [comment]
I can confirm that this is working now.
Thank you, good work, keep it up!
