### ISSUE TITLE
"analyzeAll" flag breaks pub on dart 1.8+

### ISSUE THREAD

**Issue by ewot** [playif/play_pixi#3]
The analyzeAll flag used in the $dart2js transformer in pubspec.yaml seems to have been removed in dart 1.8+. Depending on Pixi breaks the build (both pub build and from inside the dart editor) of the project with the following error:
  Unrecognized dart2js option "analyzeAll".

**Comment by nouira** [comment]
Any work around available ?

**Comment by playif** [comment]
Hi @ewot , @nouira 
I made a hot fix for this issue.
Please upgrade the package.

**Comment by nouira** [comment]
Great, thanks. That solved the issue.
